import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';
import { ProductService } from '../shared/services/product.service';
import { Product } from '../shared/models/product';
import { Router } from '@angular/router';
import { FirebaseProductService } from '../shared/services/firebase-product.service';
import { Camera, CameraResultType, CameraSource } from '@capacitor/camera';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';

@Component({
  selector: 'app-add-product',
  templateUrl: './add-product.page.html',
  styleUrls: ['./add-product.page.scss'],
})
export class AddProductPage implements OnInit {
  addProductForm: FormGroup;
  selectedCategory: string = '';
  conditions: string[] | undefined;
  submitted : boolean = false ;
  photo: any;
  imageURL: any;
  image!: any;


  constructor(private router: Router,private productService: FirebaseProductService, private sanitizer: DomSanitizer) {
    this.conditions = ['Brand New', 'Like New', 'Lightly Used', 'Well Used'];
    this.addProductForm = new FormGroup({
      name: new FormControl(''),
      price: new FormControl(0),
      image: new FormControl(''),
      category: new FormControl(''),
      dealMethod: new FormControl('Delivery'),
      details: new FormControl(''),
      condition: new FormControl('Brand New'),
      seller: new FormControl(''),
      isFavourite: new FormControl(false),
      sellerImage: new FormControl(''),
    });
  }

  selectCategory(category: string) {
    this.selectedCategory = category;
    const categoryControl = this.addProductForm.get('category');

    if (categoryControl) {
      categoryControl.setValue(category);
    } else {
      console.error('Category control not found in form');
    }
  }

  add() {
     this.submitted = true;
     if (this.addProductForm.valid) {
       const prod = new Product(
        this.addProductForm.value.name,
        this.addProductForm.value.price,
        this.photo, //No product image yet
        '', // ID will be auto generated by firebase
        this.addProductForm.value.category,
        this.addProductForm.value.dealMethod,
        this.addProductForm.value.details,
        this.addProductForm.value.condition,
        '', //No seller name yet
        false, //Products will not be favourite when its being created
        '' //No seller image yet
       ); 
       prod.imagePath = this.imageURL;
       this.productService.add(prod);
       this.router.navigate(['tabs/Marketplace']);
     }
   }

   async takePhoto() {
    this.image = await Camera.getPhoto({
    quality: 100,
    allowEditing: false,
    resultType: CameraResultType.DataUrl,
    source: CameraSource.Camera
    });
    this.photo = this.sanitizer.bypassSecurityTrustResourceUrl(this.image && (this.image.dataUrl));
    this.imageURL = this.image.dataUrl;
    }
   

  ngOnInit() {}
}
